"use client";
import "./globals.css";
import {useEffect,useState} from "react";
const empty={designation:"",manufacturer:"",model:"",serial:"",year:"",quantity:"1",condition:"gebraucht",notes:""};
export default function Home(){
 const [room,setRoom]=useState("");const [files,setFiles]=useState([]);const [items,setItems]=useState([]);const [busy,setBusy]=useState(false);const [form,setForm]=useState(empty);
 useEffect(()=>{setRoom(localStorage.getItem("inventar-room")||"");setItems(JSON.parse(localStorage.getItem("inventar-items")||"[]"))},[]);
 const saveRoom=v=>{setRoom(v);localStorage.setItem("inventar-room",v)};const persist=x=>{setItems(x);localStorage.setItem("inventar-items",JSON.stringify(x))};
 const addManual=()=>{if(!form.designation.trim())return alert("Bitte eine Bezeichnung eingeben.");persist([{...form,room,id:crypto.randomUUID()},...items]);setForm(empty)};
 const analyze=async()=>{if(!files.length)return;setBusy(true);let all=[];try{for(const f of files){const data=await new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});const q=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image:data})});const j=await q.json();if(!q.ok)throw new Error(j.error||"Analyse fehlgeschlagen");for(const x of(j.items||[]))all.push({...x,quantity:"1",condition:"gebraucht",room,id:crypto.randomUUID()})}persist([...all,...items]);setFiles([])}catch(e){alert(e.message)}finally{setBusy(false)}};
 const csv=()=>{const rows=[["Raum","Bezeichnung","Hersteller","Typ","Nr.","Baujahr","Anzahl","Zustand","Bemerkung"],...items.map(x=>[x.room,x.designation,x.manufacturer,x.model,x.serial,x.year,x.quantity,x.condition,x.notes])];const s=rows.map(r=>r.map(v=>'"'+String(v||"").replaceAll('"','""')+'"').join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([s],{type:"text/csv;charset=utf-8"}));a.download="inventar.csv";a.click()};
 const field=(k,p,type="text")=><input type={type} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={p}/>;
 return <main><div className="head"><h1>Inventar V3</h1><span className="badge">● bereit</span></div>
 <div className="card"><label>Aktueller Raum</label><input value={room} onChange={e=>saveRoom(e.target.value)} placeholder="z. B. Werkstatt / Büro 1"/><div className="muted">Bleibt gespeichert, bis du ihn änderst.</div></div>
 <div className="card"><h2>Foto-KI</h2><div className="muted">Gegenstand oder Typenschild fotografieren. Mehrere Fotos können gleichzeitig ausgewählt werden.</div><label>Fotos auswählen</label><input type="file" accept="image/*" multiple onChange={e=>setFiles([...e.target.files])}/>{files.length>0&&<p>{files.length} Foto(s) ausgewählt</p>}<button className="green" disabled={busy||!files.length} onClick={analyze}>{busy?"KI analysiert …":"Fotos analysieren & Artikel anlegen"}</button></div>
 <div className="card"><h2>Artikel manuell erfassen</h2><div className="muted">Für Schreibtische, Stühle, Rollcontainer, Regale und andere Gegenstände ohne Typenschild.</div><label>Bezeichnung *</label>{field("designation","z. B. Schreibtisch, Bürodrehstuhl, Rollcontainer")}<div className="grid"><div><label>Hersteller / Marke</label>{field("manufacturer","optional")}</div><div><label>Typ / Modell</label>{field("model","optional")}</div><div><label>Inventar-/Seriennummer</label>{field("serial","optional")}</div><div><label>Baujahr</label>{field("year","optional")}</div><div><label>Anzahl</label>{field("quantity","1","number")}</div><div><label>Zustand</label>{field("condition","z. B. gebraucht")}</div></div><label>Bemerkung</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="z. B. Gebrauchsspuren, Farbe, Ausführung"/><button onClick={addManual}>Artikel hinzufügen</button></div>
 <div className="card"><div className="head"><h2>Inventar ({items.length})</h2>{items.length>0&&<button style={{width:"auto",margin:0}} className="secondary" onClick={csv}>CSV</button>}</div>{!items.length?<p className="muted">Noch keine Artikel erfasst.</p>:items.map(x=><div className="item" key={x.id}><strong>{x.quantity&&x.quantity!=="1"?x.quantity+"× ":""}{x.designation||"Unbekannter Artikel"}</strong><div className="muted">{x.room||"Ohne Raum"}{x.manufacturer?" · "+x.manufacturer:""}{x.serial?" · Nr. "+x.serial:""}{x.year?" · Bj. "+x.year:""}{x.condition?" · "+x.condition:""}</div></div>)}</div></main>
}