"use client";
import "./globals.css";import {useEffect,useState} from "react";
const empty={designation:"",manufacturer:"",model:"",serial:"",year:"",quantity:"1",condition:"gebraucht",notes:""};
const headers=["InvNr","Bezeichnung","Anz","Gruppe (m)","Raum","LiquiE (m)","FortE (m)","Ausruf1 (m)","Ausruf2 (m)","Ergänzungen","Bemerkungen","Wartungspflichtig (0/1) (m)","W. Bemerkungen","S1 (m)","S2 (m)","S3 (m)","S4 (m)","S5 (m)"];
export default function Home(){
 const[withValuation,setWithValuation]=useState(false);const[room,setRoom]=useState("");const[files,setFiles]=useState([]);const[items,setItems]=useState([]);const[busy,setBusy]=useState(false);const[form,setForm]=useState(empty);const[audios,setAudios]=useState([]);const[dictBusy,setDictBusy]=useState(false);const[preview,setPreview]=useState([]);const[transcript,setTranscript]=useState("");
 useEffect(()=>{setRoom(localStorage.getItem("inventar-room")||"");setItems(JSON.parse(localStorage.getItem("inventar-items")||"[]"))},[]);
 const saveRoom=v=>{setRoom(v);localStorage.setItem("inventar-room",v)};const persist=x=>{setItems(x);localStorage.setItem("inventar-items",JSON.stringify(x))};
 const nextInv=()=>String(Math.max(0,...items.map(x=>Number(x.invNr)||0))+1);
 const makeDesignation=x=>{let p=[x.designation,x.manufacturer,x.model].filter(Boolean).join(" ");if(x.serial)p+=", Nr. "+x.serial;if(x.year)p+=", Baujahr "+x.year;return p.trim()};
 const addManual=()=>{if(!form.designation.trim())return alert("Bitte eine Bezeichnung eingeben.");persist([...items,{...form,designation:makeDesignation(form),invNr:nextInv(),room,id:crypto.randomUUID()}]);setForm(empty)};
 const analyze=async()=>{if(!files.length)return;setBusy(true);let all=[];try{for(const f of files){const data=await new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});const q=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image:data})});const j=await q.json();if(!q.ok)throw new Error(j.error||"Analyse fehlgeschlagen");for(const x of(j.items||[])){const n=items.length+all.length+1;all.push({...x,designation:makeDesignation(x),invNr:String(n),quantity:"1",condition:"gebraucht",room,id:crypto.randomUUID()})}}persist([...items,...all]);setFiles([])}catch(e){alert(e.message)}finally{setBusy(false)}};
 const prepareAudio=async(file)=>{if(!/\.wma$/i.test(file.name))return file;const [{FFmpeg},{fetchFile,toBlobURL}]=await Promise.all([import("@ffmpeg/ffmpeg"),import("@ffmpeg/util")]);const ffmpeg=new FFmpeg();const base="https://unpkg.com/@ffmpeg/core@0.12.10/dist/umd";await ffmpeg.load({coreURL:await toBlobURL(base+"/ffmpeg-core.js","text/javascript"),wasmURL:await toBlobURL(base+"/ffmpeg-core.wasm","application/wasm")});await ffmpeg.writeFile("input.wma",await fetchFile(file));await ffmpeg.exec(["-i","input.wma","-vn","-ac","1","-ar","12000","-b:a","16k","-f","segment","-segment_time","1200","-reset_timestamps","1","teil%03d.mp3"]);const parts=[];for(let i=0;;i++){const name="teil"+String(i).padStart(3,"0")+".mp3";try{const data=await ffmpeg.readFile(name);parts.push(new File([data.buffer],name,{type:"audio/mpeg"}))}catch{break}}ffmpeg.terminate();if(!parts.length)throw new Error("WMA konnte nicht in Audioabschnitte umgewandelt werden.");return parts};
 const importDictation=async()=>{if(!audios.length)return;setDictBusy(true);let all=[],texts=[],errors=[],activeRoom=room,next=Number(nextInv());try{for(const source of audios){try{const prepared=await prepareAudio(source);const parts=Array.isArray(prepared)?prepared:[prepared];for(const part of parts){const fd=new FormData();fd.append("audio",part);fd.append("currentRoom",activeRoom);fd.append("nextInv",String(next));const q=await fetch("/api/dictation",{method:"POST",body:fd});const raw=await q.text();let j;try{j=JSON.parse(raw)}catch{throw new Error(q.ok?"Server-Antwort konnte nicht gelesen werden.":"Serverfehler "+q.status+": "+raw.slice(0,180))}if(!q.ok)throw new Error(j.error||"Diktat fehlgeschlagen");texts.push("["+source.name+"]\\n"+(j.transcript||""));const got=Array.isArray(j.items)?j.items:[];all.push(...got);if(got.length){const last=[...got].reverse().find(x=>x.room);if(last?.room)activeRoom=last.room;next=Math.max(next,...got.map(x=>Number(x.invNr)||0))+1}}}catch(e){errors.push(source.name+": "+e.message)}}setTranscript(texts.join("\\n\\n"));setPreview((withValuation?await valuePreview(all):all).map(x=>({...x,id:crypto.randomUUID()})));if(errors.length)alert("Einige Dateien konnten nicht verarbeitet werden:\\n"+errors.join("\\n"));else if(!all.length)alert("Keine Inventarpositionen erkannt. Bitte erkannten Text und Audiodateien prüfen.")}catch(e){setTranscript(texts.join("\\n\\n"));setPreview(all.map(x=>({...x,id:crypto.randomUUID(),valuationStatus:withValuation?"Bewertung prüfen":undefined})));alert("Auswertung teilweise fehlgeschlagen: "+e.message)}finally{setDictBusy(false)}};
 const valuePreview=async(rows)=>{if(!rows.length)return rows;let result=[];for(let offset=0;offset<rows.length;offset+=25){const batch=rows.slice(offset,offset+25);try{const q=await fetch("/api/valuation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:batch})});const j=await q.json();if(!q.ok)throw new Error(j.error||"Bewertung fehlgeschlagen");result.push(...batch.map((x,i)=>{const v=(j.results||[]).find(y=>Number(y.index)===i);return {...x,valuationStatus:v?.status||"Bewertung prüfen",fort:v?.fort??null,liqui:v?.liqui??null,valuationReason:v?.reason||""}}))}catch(e){result.push(...batch.map(x=>({...x,valuationStatus:"Bewertung prüfen",fort:null,liqui:null,valuationReason:"Bewertung fehlgeschlagen: "+e.message})))}}return result};
 const acceptDictation=()=>{persist([...items,...preview]);const last=[...preview].reverse().find(x=>x.room);if(last?.room)saveRoom(last.room);setPreview([]);setTranscript("");setAudios([])};
 const updatePreview=(id,k,v)=>setPreview(preview.map(x=>x.id===id?{...x,[k]:v}:x));
 const csv=(exportItems=items)=>{const rows=[headers,...exportItems.map(x=>[x.invNr||"",x.designation||"","1","",x.room||"",x.liqui??"",x.fort??"","","",x.valuationStatus==="Bewertung prüfen"?"Bewertung prüfen":(x.valuationStatus==="Schätzwert"?"KI-Schätzwert, prüfen":""),x.notes||"","","","","","","",""])];const s="\uFEFF"+rows.map(r=>r.map(v=>'"'+String(v??"").replaceAll('"','""')+'"').join(";")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([s],{type:"text/csv;charset=utf-8"}));a.download="Inventar_Access.csv";a.click()};
 const field=(k,p,type="text")=><input type={type} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={p}/>;
 return <main><div className="head"><h1>Inventar V3</h1><span className="badge">● bereit</span></div>
 <div className="card"><label>Aktueller Raum</label><input value={room} onChange={e=>saveRoom(e.target.value)} placeholder="z. B. Werkstatt / Büro 1"/><div className="muted">Bleibt gespeichert, bis du ihn änderst.</div></div>
 <div className="card"><h2>Foto-KI</h2><div className="muted">Gegenstand oder Typenschild fotografieren. Erkannte Daten werden zu einer fertigen Bezeichnung zusammengeführt.</div><label>Fotos auswählen</label><input type="file" accept="image/*" multiple onChange={e=>setFiles([...e.target.files])}/>{files.length>0&&<p>{files.length} Foto(s) ausgewählt</p>}<button className="green" disabled={busy||!files.length} onClick={analyze}>{busy?"KI analysiert …":"Fotos analysieren & Artikel anlegen"}</button></div>
 <div className="card"><h2>Diktat importieren</h2><div className="muted">Audioaufnahme hochladen. Räume, Inventarnummern und Artikel werden automatisch erkannt und zunächst zur Prüfung angezeigt.</div><label>Bewertung beim Diktatimport</label><div className="grid"><button className={!withValuation?"green":"secondary"} disabled={dictBusy} onClick={()=>setWithValuation(false)}>Ohne Bewertung</button><button className={withValuation?"green":"secondary"} disabled={dictBusy} onClick={()=>setWithValuation(true)}>Mit Bewertung</button></div><p className="muted">Netto-Schätzwerte ohne Live-Marktrecherche. Fehlende Angaben: Bewertung prüfen.</p><label>Audio-Diktat auswählen</label><input type="file" accept="audio/*,.dss,.ds2,.wma,.m4a,.mp3,.wav,.webm,.mp4" multiple onChange={e=>setAudios([...e.target.files])}/>{audios.length>0&&<div><p><strong>{audios.length} Audiodatei(en) ausgewählt</strong></p><div className="muted">{audios.map(x=>x.name).join(", ")}</div></div>}<button className="green" disabled={!audios.length||dictBusy} onClick={importDictation}>{dictBusy?"Audiodateien werden nacheinander ausgewertet …":"Diktate auswerten"}</button>{transcript&&<details><summary>Erkannten Text anzeigen</summary><p className="muted">{transcript}</p></details>}{preview.length>0&&<div><h3>Prüfliste ({preview.length})</h3>{preview.map(x=><div className="photo" key={x.id}><div className="grid"><div><label>InvNr</label><input value={x.invNr||""} onChange={e=>updatePreview(x.id,"invNr",e.target.value)}/></div><div><label>Anzahl CSV</label><input value="1" disabled/></div></div><label>Bezeichnung</label><textarea value={x.designation||""} onChange={e=>updatePreview(x.id,"designation",e.target.value)}/><label>Raum</label><input value={x.room||""} onChange={e=>updatePreview(x.id,"room",e.target.value)}/>{withValuation&&<div className="muted">Bewertung: {x.valuationStatus||"Bewertung prüfen"} · Liqui netto: {x.liqui??"–"} € · Fortführung netto: {x.fort??"–"} € {x.valuationReason?" · "+x.valuationReason:""}</div>}<label>Bemerkungen</label><input value={x.notes||""} onChange={e=>updatePreview(x.id,"notes",e.target.value)}/></div>)}<div className="head"><h3>Erkannte Inventarpositionen</h3><button className="secondary" style={{width:"auto"}} onClick={()=>csv(preview)}>Prüfliste als Access-CSV</button></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["InvNr","Bezeichnung","Raum","Liqui netto","Fortführung netto","Status"].map(h=><th key={h} style={{padding:8,textAlign:"left",borderBottom:"1px solid #ddd"}}>{h}</th>)}</tr></thead><tbody>{preview.map(x=><tr key={x.id}>{[x.invNr,x.designation,x.room,x.liqui??"–",x.fort??"–",x.valuationStatus||"Ohne Bewertung"].map((v,i)=><td key={i} style={{padding:8,borderBottom:"1px solid #eee",minWidth:i===1?240:70}}>{v}</td>)}</tr>)}</tbody></table></div><button onClick={acceptDictation}>Alle geprüften Positionen übernehmen</button></div>}</div>
 <div className="card"><h2>Artikel manuell erfassen</h2><div className="muted">Auch Sammelpositionen möglich, z. B. „Büroraumausstattung: Schreibtisch, Bürodrehstuhl, Rollcontainer“.</div><label>Bezeichnung *</label>{field("designation","z. B. Büroraumausstattung: Schreibtisch, Bürodrehstuhl, Rollcontainer")}<div className="grid"><div><label>Hersteller / Marke</label>{field("manufacturer","optional")}</div><div><label>Typ / Modell</label>{field("model","optional")}</div><div><label>Seriennummer</label>{field("serial","optional")}</div><div><label>Baujahr</label>{field("year","optional")}</div><div><label>Anzahl</label>{field("quantity","1","number")}</div><div><label>Zustand</label>{field("condition","optional")}</div></div><label>Bemerkungen</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button onClick={addManual}>Artikel hinzufügen</button></div>
 <div className="card"><div className="head"><h2>Inventar ({items.length})</h2>{items.length>0&&<button style={{width:"auto",margin:0}} className="secondary" onClick={csv}>Access-CSV</button>}</div>{!items.length?<p className="muted">Noch keine Artikel erfasst.</p>:items.map(x=><div className="item" key={x.id}><strong>{x.invNr?x.invNr+" · ":""}{x.designation}</strong><div className="muted">Anz. {x.quantity||1} · {x.room||"Ohne Raum"}{x.notes?" · "+x.notes:""}</div></div>)}</div></main>
}